### ISSUE TITLE
It doesn't do anything

### ISSUE THREAD

**Issue by hediet** [ghmcadams/vscode-lintlens#16]
I really like the idea of your extension!

However, I've installed it and it does nothing. No lens in my `.eslintrc` file, even though I installed the most recent `eslint`.
It neither works with the current VS Code nor the insider with every other extension disabled.

**Comment by ghmcadams** [comment]
Thanks for sharing. I’m sorry the extension doesn’t work. I discovered that the latest version of eslint made private a function that lintlens depends on in order to function. I’m searching for another way to make it work.  For now, the only work-around is to downgrade eslint to version 5.  I will inform of any progress.

Gabriel

**Comment by ghmcadams** [comment]
I believe this issue has been resolved.  Please try again with the latest version of eslint.
